name: CI/CD for Nextjs with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.DOTENV_FILE }}" | base64 -d > .env

      - name: Login to Harbor registry
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{secrets.HARBOR_DOMAIN}} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          docker build --network=host -t ${{secrets.HARBOR_DOMAIN}}/${{ secrets.HARBOR_REPO_FE }}/next-app:${{ github.sha }} .
          docker push ${{secrets.HARBOR_DOMAIN}}/${{ secrets.HARBOR_REPO_FE }}/next-app:${{ github.sha }}

      - name: Update and restart containers
        run: |
          DEPLOY_DIR=/home/github-runner/deploy/
          rm -rf $DEPLOY_DIR
          mkdir -p $DEPLOY_DIR
          cp -r . $DEPLOY_DIR
          pwd
          ls -l
          cd $DEPLOY_DIR
          sed -i "s|image:.*|image: ${{secrets.HARBOR_DOMAIN}}/${{ secrets.HARBOR_REPO_FE }}/next-app:${{ github.sha }}|" docker-compose.yml
          docker compose down --timeout 30
          docker compose up -d
          docker image prune -af --filter "until=24h"